---
language: go
go:
- 1.1.1
- tip
env:
  global:
  - PATH=$HOME/bin:$PATH
  - ARTIFACTS_AWS_REGION=us-east-1
  - ARTIFACTS_S3_BUCKET=modcloth-public-travis-artifacts
  - secure: ! 'Tr8IJkujk98weB3iHmxwpFXZdUt0QlzYNrrP3h7TDpTs2VuXh+RM4m8TYsj4

      uM87QO4a/IuY2pV9LaJmJBaWhNW+q+AHDrLfl5/gcQY5LsSNIxaCMSw7H42U

      kVGRl90+GYw8bJeTgobAu25qvL3EZ65+kdDATO8yLmiUNi38qF0='
  - secure: ! 'kCfvqAib4Y/U82PzDvZ1/YYx//qy0JMeUbt/C7pC2cuoC0XctUuY2FfFGOQG

      gmRf/bRJ5v95EU8s1pgGe3pX/FEEVXMrGSr1huie4/aDquSEzv0LN+YcW9B+

      zA5Q68KlipnZrt/eyxKrGaG3SqcllzghJqenAarQj8r65BjC65I='
install: make build
script: make test golden
after_success:
- if [ "$TRAVIS_GO_VERSION" == "go1.1.1" ] ; then
    mkdir -p $HOME/bin ;
    pushd $HOME/bin ;
    curl -s -O https://raw.github.com/modcloth-labs/travis-buddy/master/tb ;
    chmod +x tb ;
    popd ;
    if tb nopr ; then
      tb setup-aws ;
      tb install-travis-artifacts ;
      tb upload-go-artifacts --public ;
      tb upload-artifact $TRAVIS_BUILD_DIR/worm.d
        artifacts/binaries/$(go env GOOS)/$(go env GOARCH)/hookworm/$TRAVIS_COMMIT/ --public ;
      tb upload-artifact $TRAVIS_BUILD_DIR/worm.d
        artifacts/binaries/$(go env GOOS)/$(go env GOARCH)/hookworm/$TRAVIS_BRANCH/ --public ;
    fi ;
  fi
notifications:
  email:
    recipients:
    - d.buch@modcloth.com
    - r.mckinstry@modcloth.com
  webhooks:
  - http://meatballhat.no-ip.biz:9988/travis
