---
language: go
go:
- 1.1.1
- tip
install: make build
script: make test golden
notifications:
  email:
    recipients:
     - d.buch@modcloth.com
     - r.mckinstry@modcloth.com
  webhooks:
  - http://meatballhat.no-ip.biz:9988/travis
