---
language: go
go:
- 1.1.2
- tip
env:
  global:
  - PATH=$HOME/bin:$PATH
  - ARTIFACTS_AWS_REGION=us-east-1
  - ARTIFACTS_S3_BUCKET=modcloth-public-travis-artifacts
  - secure: ! 'Tr8IJkujk98weB3iHmxwpFXZdUt0QlzYNrrP3h7TDpTs2VuXh+RM4m8TYsj4

      uM87QO4a/IuY2pV9LaJmJBaWhNW+q+AHDrLfl5/gcQY5LsSNIxaCMSw7H42U

      kVGRl90+GYw8bJeTgobAu25qvL3EZ65+kdDATO8yLmiUNi38qF0='
  - secure: ! 'kCfvqAib4Y/U82PzDvZ1/YYx//qy0JMeUbt/C7pC2cuoC0XctUuY2FfFGOQG

      gmRf/bRJ5v95EU8s1pgGe3pX/FEEVXMrGSr1huie4/aDquSEzv0LN+YcW9B+

      zA5Q68KlipnZrt/eyxKrGaG3SqcllzghJqenAarQj8r65BjC65I='
install:
- make build
- gem install rubocop -v '0.12.0'
script: rubocop && make test && make golden
after_success:
- if [ "$TRAVIS_GO_VERSION" == "go1.1.2" ] ; then
    mkdir -p $HOME/bin ;
    pushd $HOME/bin ;
    curl -s -O https://raw.github.com/modcloth-labs/travis-buddy/master/tb ;
    chmod +x tb ;
    popd ;
    if tb nopr ; then
      mkdir -p $TRAVIS_BUILD_DIR/build/hookworm ;
      cd $TRAVIS_BUILD_DIR ;
      git archive HEAD | bzip2 > $TRAVIS_BUILD_DIR/build/hookworm/hookworm-src.tar.bz2 ;
      tb setup-aws ;
      tb install-travis-artifacts ;
      tb upload-go-artifacts --public ;
    fi ;
  fi
notifications:
  email:
    recipients:
    - github+hookworm@modcloth.com
