#!/usr/bin/env ruby
# -*- coding: utf-8 -*-
# vim:fileencoding=utf-8

exe = "#{ENV['GOPATH'].split(':').first}/bin/hookworm-server"
usage = `#{exe} -h 2>&1`.chomp
handler_usage = ''

Dir.glob("#{File.expand_path('../', __FILE__)}/worm.d/*.*").each do |handler|
  handler_usage << File.read(handler).split($/).select do |l|
    l =~ %r{^(#|//)\+\s?}
  end.map do |l|
    l.sub(%r{^(#|//)\+\s?}, '')
  end.join($/)
  handler_usage << "\n\n"
end

$stdout.puts $stdin.read.sub(/___USAGE___/, usage)
                        .sub(/___HANDLER_USAGE___/, handler_usage)
