#!/usr/bin/env ruby
# vim:fileencoding=utf-8

require 'fileutils'
require 'minitest/spec'
require 'net/http'

require_relative '.golden/bits'
require_relative '.golden/hookworm_server_runner'
require_relative '.golden/fakesmtpd_runner'

include Bits
include FileUtils

$fakesmtpd_server = FakeSMTPdRunner.new(
  port: "#{rand(13100..13109)}",
  dir: File.expand_path('../log/emails', __FILE__),
  pidfile: File.expand_path('../log/fakesmtpd.pid', __FILE__)
)

$servers = {
  null: HookwormServerRunner.new(
    '-a' => ":#{rand(12100..12109)}",
    '-P' => File.expand_path('../log/hookworm-server-null.pid', __FILE__),
    start: Time.now.utc,
  ),
  debug: HookwormServerRunner.new(
    '-a' => ":#{rand(12110..12119)}",
    '-d' => nil,
    '-P' => File.expand_path('../log/hookworm-server-debug.pid', __FILE__),
    '-b' => '^master$,^develop$',
    '-e' => "smtp://localhost:#{$fakesmtpd_server.port}",
    '-f' => 'hookworm-runtests@testing.local',
    '-r' => 'hookworm-self@testing.local',
    start: Time.now.utc,
  )
}

$servers.each do |name,server|
  describe "#{name} server receiving hook payloads" do
    it 'accepts valid POSTs' do
      post_request(
        port: server.port, body: payload(:valid)
      ).code.must_equal '204'
    end

    it 'rejects invalid POSTs' do
      post_request(
        port: server.port, body: payload(:bogus)
      ).code.must_equal '400'
    end
  end
end

def main(argv = [].freeze)
  at_exit do
    $fakesmtpd_server.stop
    $servers.each do |_,server|
      server.stop
    end
  end

  Dir.chdir(File.expand_path('../', __FILE__)) do
    mkdir_p('./log')
    $fakesmtpd_server.start
    $servers.each do |_,runner|
      runner.start
    end
  end

  MiniTest::Unit.output = MiniTestReporter.new
  exit_code = MiniTest::Unit.new.run(argv)

  if exit_code == 0
    $stderr.puts BRIGHT_GREEN
    $stderr.puts <<-EOF.gsub(/^ {4}/, '')
      ✓✓      ✓✓ ✓✓✓✓ ✓✓    ✓✓
      ✓✓  ✓✓  ✓✓  ✓✓  ✓✓✓   ✓✓
      ✓✓  ✓✓  ✓✓  ✓✓  ✓✓✓✓  ✓✓
      ✓✓  ✓✓  ✓✓  ✓✓  ✓✓ ✓✓ ✓✓
      ✓✓  ✓✓  ✓✓  ✓✓  ✓✓  ✓✓✓✓
      ✓✓  ✓✓  ✓✓  ✓✓  ✓✓   ✓✓✓
       ✓✓✓  ✓✓✓  ✓✓✓✓ ✓✓    ✓✓
    EOF
    $stderr.puts RESET
  else
    $stderr.puts BRIGHT_RED
    $stderr.puts <<-EOF.gsub(/^ {4}/, '')
      ✘✘✘✘✘✘✘✘    ✘✘✘    ✘✘✘✘ ✘✘
      ✘✘         ✘✘ ✘✘    ✘✘  ✘✘
      ✘✘        ✘✘   ✘✘   ✘✘  ✘✘
      ✘✘✘✘✘✘   ✘✘     ✘✘  ✘✘  ✘✘
      ✘✘       ✘✘✘✘✘✘✘✘✘  ✘✘  ✘✘
      ✘✘       ✘✘     ✘✘  ✘✘  ✘✘
      ✘✘       ✘✘     ✘✘ ✘✘✘✘ ✘✘✘✘✘✘✘✘
    EOF
    $stderr.puts RESET

    $servers.each { |_,server| server.dump_log }
  end

  exit exit_code
end

if __FILE__ == $0
  main(ARGV)
end
